* Confidence in public institutions is critical in containing the COVID-19 pandemic
* Anna Adamecz-Völgyi and Ágnes Szabó-Morvai
* 2021.05.25.


drop if country==""
replace country="Egypt" if country=="Egypt, Arab Rep."
replace country="Slovakia" if country=="Slovak Republic"
replace country="Congo" if country=="Congo, Rep."
replace country="Democratic Republic of Congo" if country=="Congo, Dem. Rep."
replace country="Russia" if country=="Russian Federation"
replace country="Iran" if country=="Iran, Islamic Rep." | country=="Iran (Islamic Republic of)"
replace country="South Korea" if country=="Korea, Rep."
replace country="Kyrgyzstan" if country=="Kyrgyz Republic"
replace country="Czechia" if country=="Czech Republic"
replace country="Bosnia and Herzegovina" if country=="Bosnia" | country=="Bosnia Herzegovina"
replace country="Argentina" if country=="Argenti"
replace country="Bosnia and Herzegovina" if country=="Bosnia and Herzegovi"
replace country="Botswana" if country=="Botswa"
replace country="Canada" if country=="Cada"
replace country="China" if country=="Chi"
replace country="Ghana" if country=="Gha"
replace country="Cote d'Ivoire" if country=="Ivory Coast" |  country=="Côte d'Ivoire" |  country=="Côte d’Ivoire"
replace country="United Arab Emirates" if country=="UAE"
replace country="Vietnam" if country=="Vietm" | country=="Viet Nam"

replace country="United Kingdom" if country=="Great Britain"
replace country="Hong Kong" if country=="Hong Kong SAR"
replace country="Hong Kong" if country=="Hong Kong SAR, China"
replace country="Macau, China" if country=="Macau SAR"
replace country="Taiwan" if country=="Taiwan ROC"
replace country="Bahamas" if  country=="Bahamas, The"
replace country="Brunei"   if  country=="Brunei Darussalam"
replace country="Cape Verde"   if  country=="Cabo Verde"
replace country="Gambia" if  country=="Gambia, The"
replace country="Saint Vincent and the Grenadines" if  country=="St. Vincent and the Grenadines"country
replace country="Syria" if  country=="Syrian Arab Republic"
*replace country="Taiwan" if  country=="
replace country="Venezuela" if  country=="Venezuela, RB" | country=="Venezuela (Bolivarian Republic of)"
replace country="Yemen" if  country=="Yemen, Rep."
replace country="North Macedonia" if  country=="Macedonia" | country=="The former Yugoslav Republic of Macedonia"
replace country="United States" if  country=="United States of America"
replace country="Democratic Republic of Congo" if  country=="Democratic Republic of the Congo"
replace country="Bolivia"  if  country=="Bolivia (Plurinational State of)"
replace country="United Kingdom"  if  country=="United Kingdom of Great Britain and Northern Ireland"
replace country="South Korea"   if  country=="Republic of Korea"
replace country="Moldova"  if  country=="Republic of Moldova"


replace country="Australia" if  country=="australia"
replace country="Brazil"  if  country=="brazil"
replace country="Canada"  if  country=="canada"
replace country="China"  if  country=="china"
replace country="Denmark"  if  country=="denmark"
replace country="Finland"  if  country=="finland"
replace country="France"  if  country=="france"
replace country="Germany"  if  country=="germany"
replace country="Hong Kong"  if  country=="hong-kong"
replace country="India"  if  country=="india"
replace country="Indonesia"  if  country=="indonesia"
replace country="Italy"  if  country=="italy"
replace country="Japan"  if  country=="japan"
replace country="Malaysia"  if  country=="malaysia"
replace country="Mexico"  if  country=="mexico"
replace country="Netherlands"  if  country=="netherlands"
replace country="Norway"  if  country=="norway"
replace country="Philippines"  if  country=="philippines"
replace country="Saudi Arabia"  if  country=="saudi-arabia"
replace country="Singapore"  if  country=="singapore"
replace country="South Korea"  if  country=="south-korea"
replace country="Spain"  if  country=="spain"
replace country="Sweden"  if  country=="sweden"
replace country="Taiwan"  if  country=="taiwan"
replace country="Thailand"  if  country=="thailand"
replace country="United Arab Emirates"  if  country=="united-arab-emirates"
replace country="United Kingdom"  if  country=="united-kingdom"
replace country="United States"  if  country=="united-states"
replace country="Vietnam"  if  country=="vietnam"


